import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./smoothScroll";
import FlyFazaiaNavbar from "./home_comps/navBar";
import Footer from "./home_comps/footer";
import { NavServer } from "./home_comps/navServerAction";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("root rendered");
  
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-grid-background`}
      >
        <SmoothScroll/>
       
    <Suspense fallback={<p className="text-black text-6xl">LOADING</p>}><NavServer/></Suspense> 
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
