import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./smoothScroll";
import FlyFazaiaNavbar from "./home_comps/navBar";
import Footer from "./home_comps/footer";
import { NavServer } from "./home_comps/navServerAction";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FlyFazaia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("root rendered");
  
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-grid-background`}
      >
        <SmoothScroll/>
       
    <Suspense fallback={<div className="flex items-center justify-center lg:mt-44 h-64">
                  <div className="text-center">
                    <div className="w-16 h-16 border-4 border-indigo-600 border-t-transparent 
                                  rounded-full animate-spin mx-auto mb-4"></div>
                    {/* <p className="text-indigo-700 text-xl font-bold">Loading...</p> */}
                  </div>
                </div>}><NavServer/></Suspense> 
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
